// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: count_sum.proto

package com.hny.hbase.coprocessor;

public final class CountAndSumProtocol {
  private CountAndSumProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CountAndSumRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string family = 1;
    /**
     * <code>required string family = 1;</code>
     */
    boolean hasFamily();
    /**
     * <code>required string family = 1;</code>
     */
    String getFamily();
    /**
     * <code>required string family = 1;</code>
     */
    com.google.protobuf.ByteString
        getFamilyBytes();

    // required string column = 2;
    /**
     * <code>required string column = 2;</code>
     */
    boolean hasColumn();
    /**
     * <code>required string column = 2;</code>
     */
    String getColumn();
    /**
     * <code>required string column = 2;</code>
     */
    com.google.protobuf.ByteString
        getColumnBytes();
  }
  /**
   * Protobuf type {@code CountAndSumRequest}
   */
  public static final class CountAndSumRequest extends
      com.google.protobuf.GeneratedMessage
      implements CountAndSumRequestOrBuilder {
    // Use CountAndSumRequest.newBuilder() to construct.
    private CountAndSumRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CountAndSumRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CountAndSumRequest defaultInstance;
    public static CountAndSumRequest getDefaultInstance() {
      return defaultInstance;
    }

    public CountAndSumRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CountAndSumRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              family_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              column_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_CountAndSumRequest_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_CountAndSumRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumRequest.class, com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<CountAndSumRequest> PARSER =
        new com.google.protobuf.AbstractParser<CountAndSumRequest>() {
      public CountAndSumRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CountAndSumRequest(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<CountAndSumRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string family = 1;
    public static final int FAMILY_FIELD_NUMBER = 1;
    private Object family_;
    /**
     * <code>required string family = 1;</code>
     */
    public boolean hasFamily() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string family = 1;</code>
     */
    public String getFamily() {
      Object ref = family_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          family_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string family = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFamilyBytes() {
      Object ref = family_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        family_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string column = 2;
    public static final int COLUMN_FIELD_NUMBER = 2;
    private Object column_;
    /**
     * <code>required string column = 2;</code>
     */
    public boolean hasColumn() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string column = 2;</code>
     */
    public String getColumn() {
      Object ref = column_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          column_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string column = 2;</code>
     */
    public com.google.protobuf.ByteString
        getColumnBytes() {
      Object ref = column_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        column_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      family_ = "";
      column_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasFamily()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasColumn()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFamilyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getColumnBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFamilyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getColumnBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumRequest)) {
        return super.equals(obj);
      }
      com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumRequest other = (com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumRequest) obj;

      boolean result = true;
      result = result && (hasFamily() == other.hasFamily());
      if (hasFamily()) {
        result = result && getFamily()
            .equals(other.getFamily());
      }
      result = result && (hasColumn() == other.hasColumn());
      if (hasColumn()) {
        result = result && getColumn()
            .equals(other.getColumn());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasFamily()) {
        hash = (37 * hash) + FAMILY_FIELD_NUMBER;
        hash = (53 * hash) + getFamily().hashCode();
      }
      if (hasColumn()) {
        hash = (37 * hash) + COLUMN_FIELD_NUMBER;
        hash = (53 * hash) + getColumn().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CountAndSumRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_CountAndSumRequest_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_CountAndSumRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumRequest.class, com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumRequest.Builder.class);
      }

      // Construct using com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        family_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        column_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_CountAndSumRequest_descriptor;
      }

      public com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumRequest getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      public com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumRequest build() {
        com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumRequest buildPartial() {
        com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumRequest result = new com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.family_ = family_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.column_ = column_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumRequest) {
          return mergeFrom((com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumRequest other) {
        if (other == getDefaultInstance()) return this;
        if (other.hasFamily()) {
          bitField0_ |= 0x00000001;
          family_ = other.family_;
          onChanged();
        }
        if (other.hasColumn()) {
          bitField0_ |= 0x00000002;
          column_ = other.column_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFamily()) {
          
          return false;
        }
        if (!hasColumn()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string family = 1;
      private Object family_ = "";
      /**
       * <code>required string family = 1;</code>
       */
      public boolean hasFamily() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string family = 1;</code>
       */
      public String getFamily() {
        Object ref = family_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          family_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string family = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFamilyBytes() {
        Object ref = family_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          family_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string family = 1;</code>
       */
      public Builder setFamily(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        family_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string family = 1;</code>
       */
      public Builder clearFamily() {
        bitField0_ = (bitField0_ & ~0x00000001);
        family_ = getDefaultInstance().getFamily();
        onChanged();
        return this;
      }
      /**
       * <code>required string family = 1;</code>
       */
      public Builder setFamilyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        family_ = value;
        onChanged();
        return this;
      }

      // required string column = 2;
      private Object column_ = "";
      /**
       * <code>required string column = 2;</code>
       */
      public boolean hasColumn() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string column = 2;</code>
       */
      public String getColumn() {
        Object ref = column_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          column_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string column = 2;</code>
       */
      public com.google.protobuf.ByteString
          getColumnBytes() {
        Object ref = column_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          column_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string column = 2;</code>
       */
      public Builder setColumn(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        column_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string column = 2;</code>
       */
      public Builder clearColumn() {
        bitField0_ = (bitField0_ & ~0x00000002);
        column_ = getDefaultInstance().getColumn();
        onChanged();
        return this;
      }
      /**
       * <code>required string column = 2;</code>
       */
      public Builder setColumnBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        column_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CountAndSumRequest)
    }

    static {
      defaultInstance = new CountAndSumRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CountAndSumRequest)
  }

  public interface CountAndSumResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 count = 1 [default = 0];
    /**
     * <code>required int64 count = 1 [default = 0];</code>
     */
    boolean hasCount();
    /**
     * <code>required int64 count = 1 [default = 0];</code>
     */
    long getCount();

    // required double sum = 2 [default = 0];
    /**
     * <code>required double sum = 2 [default = 0];</code>
     */
    boolean hasSum();
    /**
     * <code>required double sum = 2 [default = 0];</code>
     */
    double getSum();
  }
  /**
   * Protobuf type {@code CountAndSumResponse}
   */
  public static final class CountAndSumResponse extends
      com.google.protobuf.GeneratedMessage
      implements CountAndSumResponseOrBuilder {
    // Use CountAndSumResponse.newBuilder() to construct.
    private CountAndSumResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CountAndSumResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CountAndSumResponse defaultInstance;
    public static CountAndSumResponse getDefaultInstance() {
      return defaultInstance;
    }

    public CountAndSumResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CountAndSumResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              count_ = input.readInt64();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              sum_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_CountAndSumResponse_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_CountAndSumResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse.class, com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<CountAndSumResponse> PARSER =
        new com.google.protobuf.AbstractParser<CountAndSumResponse>() {
      public CountAndSumResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CountAndSumResponse(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<CountAndSumResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 count = 1 [default = 0];
    public static final int COUNT_FIELD_NUMBER = 1;
    private long count_;
    /**
     * <code>required int64 count = 1 [default = 0];</code>
     */
    public boolean hasCount() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 count = 1 [default = 0];</code>
     */
    public long getCount() {
      return count_;
    }

    // required double sum = 2 [default = 0];
    public static final int SUM_FIELD_NUMBER = 2;
    private double sum_;
    /**
     * <code>required double sum = 2 [default = 0];</code>
     */
    public boolean hasSum() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double sum = 2 [default = 0];</code>
     */
    public double getSum() {
      return sum_;
    }

    private void initFields() {
      count_ = 0L;
      sum_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, count_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, sum_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, count_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, sum_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse)) {
        return super.equals(obj);
      }
      com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse other = (com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse) obj;

      boolean result = true;
      result = result && (hasCount() == other.hasCount());
      if (hasCount()) {
        result = result && (getCount()
            == other.getCount());
      }
      result = result && (hasSum() == other.hasSum());
      if (hasSum()) {
        result = result && (Double.doubleToLongBits(getSum())    == Double.doubleToLongBits(other.getSum()));
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasCount()) {
        hash = (37 * hash) + COUNT_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(getCount());
      }
      if (hasSum()) {
        hash = (37 * hash) + SUM_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(
            Double.doubleToLongBits(getSum()));
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CountAndSumResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_CountAndSumResponse_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_CountAndSumResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse.class, com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse.Builder.class);
      }

      // Construct using com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        count_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        sum_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_CountAndSumResponse_descriptor;
      }

      public com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      public com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse build() {
        com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse buildPartial() {
        com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse result = new com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.count_ = count_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sum_ = sum_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse) {
          return mergeFrom((com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse other) {
        if (other == getDefaultInstance()) return this;
        if (other.hasCount()) {
          setCount(other.getCount());
        }
        if (other.hasSum()) {
          setSum(other.getSum());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCount()) {
          
          return false;
        }
        if (!hasSum()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 count = 1 [default = 0];
      private long count_ ;
      /**
       * <code>required int64 count = 1 [default = 0];</code>
       */
      public boolean hasCount() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 count = 1 [default = 0];</code>
       */
      public long getCount() {
        return count_;
      }
      /**
       * <code>required int64 count = 1 [default = 0];</code>
       */
      public Builder setCount(long value) {
        bitField0_ |= 0x00000001;
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 count = 1 [default = 0];</code>
       */
      public Builder clearCount() {
        bitField0_ = (bitField0_ & ~0x00000001);
        count_ = 0L;
        onChanged();
        return this;
      }

      // required double sum = 2 [default = 0];
      private double sum_ ;
      /**
       * <code>required double sum = 2 [default = 0];</code>
       */
      public boolean hasSum() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double sum = 2 [default = 0];</code>
       */
      public double getSum() {
        return sum_;
      }
      /**
       * <code>required double sum = 2 [default = 0];</code>
       */
      public Builder setSum(double value) {
        bitField0_ |= 0x00000002;
        sum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double sum = 2 [default = 0];</code>
       */
      public Builder clearSum() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sum_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CountAndSumResponse)
    }

    static {
      defaultInstance = new CountAndSumResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CountAndSumResponse)
  }

  /**
   * Protobuf service {@code RowCountAndSumService}
   */
  public static abstract class RowCountAndSumService
      implements com.google.protobuf.Service {
    protected RowCountAndSumService() {}

    public interface Interface {
      /**
       * <code>rpc getCountAndSum(.CountAndSumRequest) returns (.CountAndSumResponse);</code>
       */
      public abstract void getCountAndSum(
              com.google.protobuf.RpcController controller,
              com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumRequest request,
              com.google.protobuf.RpcCallback<com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new RowCountAndSumService() {
        @Override
        public  void getCountAndSum(
            com.google.protobuf.RpcController controller,
            com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumRequest request,
            com.google.protobuf.RpcCallback<com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse> done) {
          impl.getCountAndSum(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.getCountAndSum(controller, (com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumRequest)request);
            default:
              throw new AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumRequest.getDefaultInstance();
            default:
              throw new AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse.getDefaultInstance();
            default:
              throw new AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc getCountAndSum(.CountAndSumRequest) returns (.CountAndSumResponse);</code>
     */
    public abstract void getCountAndSum(
        com.google.protobuf.RpcController controller,
        com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumRequest request,
        com.google.protobuf.RpcCallback<com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.hny.hbase.coprocessor.CountAndSumProtocol.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.getCountAndSum(controller, (com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumRequest)request,
            com.google.protobuf.RpcUtil.<com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse>specializeCallback(
              done));
          return;
        default:
          throw new AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumRequest.getDefaultInstance();
        default:
          throw new AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse.getDefaultInstance();
        default:
          throw new AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends com.hny.hbase.coprocessor.CountAndSumProtocol.RowCountAndSumService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void getCountAndSum(
          com.google.protobuf.RpcController controller,
          com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumRequest request,
          com.google.protobuf.RpcCallback<com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse.class,
            com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse getCountAndSum(
              com.google.protobuf.RpcController controller,
              com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse getCountAndSum(
          com.google.protobuf.RpcController controller,
          com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumRequest request)
          throws com.google.protobuf.ServiceException {
        return (com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.hny.hbase.coprocessor.CountAndSumProtocol.CountAndSumResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:RowCountAndSumService)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CountAndSumRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CountAndSumRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CountAndSumResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CountAndSumResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017count_sum.proto\"4\n\022CountAndSumRequest\022" +
      "\016\n\006family\030\001 \002(\t\022\016\n\006column\030\002 \002(\t\"7\n\023Count" +
      "AndSumResponse\022\020\n\005count\030\001 \002(\003:\0010\022\016\n\003sum\030" +
      "\002 \002(\001:\00102T\n\025RowCountAndSumService\022;\n\016get" +
      "CountAndSum\022\023.CountAndSumRequest\032\024.Count" +
      "AndSumResponseB8\n\031com.hny.hbase.coproces" +
      "sorB\023CountAndSumProtocolH\001\210\001\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_CountAndSumRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_CountAndSumRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CountAndSumRequest_descriptor,
              new String[] { "Family", "Column", });
          internal_static_CountAndSumResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_CountAndSumResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CountAndSumResponse_descriptor,
              new String[] { "Count", "Sum", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
